# 01-03 판다스(Pandas) and 넘파이(Numpy) and 맷플롭립(Matplotlib)

## 1. 판다스(Pandas)
- 파이썬 데이터 처리를 위한 라이브러리
- 데이터 분석과 같은 작업에서 필수 

In [2]:
!pip install pandas

  Using cached pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
  Using cached tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.6 MB 11.1 MB/s eta 0:00:01
   ----- ---------------------------------- 1.5/11.6 MB 16.3 MB/s eta 0:00:01
   --------- ------------------------------ 2.8/11.6 MB 19.8 MB/s eta 0:00:01
   -------------- ------------------------- 4.1/11.6 MB 21.7 MB/s eta 0:00:01
   --------------- ------------------------ 4.5/11.6 MB 22.3 MB/s eta 0:00:01
   ------------------ --------------------- 5.3/11.6 MB 19.9 MB/s eta 0:00:01
   --------------------- ------------------ 6.3/11.6 MB 19.1 MB/s eta 0:00:01
   ---------------------------- ----------- 8.4/11.6 MB 22.4 MB/s eta 0:00:01
   ------------------------------------- -- 10.8/11.6 MB 28.5 MB/s eta 0:00:01
   ---------------------

In [3]:
import pandas as pd
pd.__version__

'2.2.2'

In [4]:
sr = pd.Series([17000, 18000, 1000, 5000],
               index=["피자", "치킨", "콜라", "맥주"])
print('시리즈 출력 :')
print('-'*15)
print(sr)

시리즈 출력 :
---------------
피자    17000
치킨    18000
콜라     1000
맥주     5000
dtype: int64


In [6]:
values = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
index = ['one', 'two', 'three']
columns = ['A', 'B', 'C']

df = pd.DataFrame(values, index=index, columns=columns)

print('데이터프레임 출력 :')
print('-'*18)
print(df)

데이터프레임 출력 :
------------------
       A  B  C
one    1  2  3
two    4  5  6
three  7  8  9


In [7]:
print('데이터프레임의 인덱스 : {}'.format(df.index))
print('데이터프레임의 열이름: {}'.format(df.columns))
print('데이터프레임의 값 :')
print('-'*18)
print(df.values)

데이터프레임의 인덱스 : Index(['one', 'two', 'three'], dtype='object')
데이터프레임의 열이름: Index(['A', 'B', 'C'], dtype='object')
데이터프레임의 값 :
------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 1) 데이터프레임 생성

In [10]:
# 리스트로 생성
data = [
    ['1000', 'Steve', 90.72], 
    ['1001', 'James', 78.09], 
    ['1002', 'Doyeon', 98.43], 
    ['1003', 'Jane', 64.19], 
    ['1004', 'Pilwoong', 81.30],
    ['1005', 'Tony', 99.14],
]

df = pd.DataFrame(data)
df

0         1      2
0  1000     Steve  90.72
1  1001     James  78.09
2  1002    Doyeon  98.43
3  1003      Jane  64.19
4  1004  Pilwoong  81.30
5  1005      Tony  99.14

In [9]:
# 열 지정
df = pd.DataFrame(data, columns=['학번', '점수', '이름'])
df

학번        점수     이름
0  1000     Steve  90.72
1  1001     James  78.09
2  1002    Doyeon  98.43
3  1003      Jane  64.19
4  1004  Pilwoong  81.30
5  1005      Tony  99.14

In [11]:
# 딕셔너리로 생성하기
data = {
    '학번' : ['1000', '1001', '1002', '1003', '1004', '1005'],
    '이름' : [ 'Steve', 'James', 'Doyeon', 'Jane', 'Pilwoong', 'Tony'],
    '점수': [90.72, 78.09, 98.43, 64.19, 81.30, 99.14]
    }

df = pd.DataFrame(data)
df

학번        이름     점수
0  1000     Steve  90.72
1  1001     James  78.09
2  1002    Doyeon  98.43
3  1003      Jane  64.19
4  1004  Pilwoong  81.30
5  1005      Tony  99.14

### 2) 데이터프레임 조회
- df.head(n)
- df.tail(n)
- df['열이름']

In [12]:
df.head(3)

학번      이름     점수
0  1000   Steve  90.72
1  1001   James  78.09
2  1002  Doyeon  98.43

In [13]:
df['학번']

0    1000
1    1001
2    1002
3    1003
4    1004
5    1005
Name: 학번, dtype: object

### 3) 외부 데이터 읽기
- Pandas는 CSV, 텍스트, Excel, SQL, HTML, JSON 등을 읽고 데이터프레임 생성 가능 

In [ ]:
df = pd.read_csv('example.csv')
df

## 2. Numpy
- 수치 데이터를 다루는 파이썬 패키지 
- 다차원 행렬 자료구조인 ndarray를 통해 벡터 및 행렬을 사용하는 선형 대수 계산에서 주로 사용
- 편의성뿐만 아니라, 속도면에서 순수 파이썬에 비해 압도적으로 빠르다. 

In [14]:
!pip install numpy

In [15]:
import numpy as np
np.__version__

'1.24.3'

### 1) np.array()
- Numpy의 핵심은 ndarray
- np.array()는 리스트, 튜플, 배열로부터 ndarray 생성

In [16]:
# 1차원 배열
vec = np.array([1,2,3,4,5])
vec

array([1, 2, 3, 4, 5])

In [17]:
# 2차원 배열
mat = np.array([[10,20,30],[60,70,80]])
mat

array([[10, 20, 30],
       [60, 70, 80]])

In [20]:
print(type(vec))

<class 'numpy.ndarray'>


In [21]:
print(type(mat))

<class 'numpy.ndarray'>


- Numpy 배열에서는 축의개수(ndim)과 크기(shape)라는 개념이 존재

In [22]:
print(vec.ndim)
print(vec.shape)

1
(5,)


In [23]:
print(mat.ndim)
print(mat.shape)

2
(2, 3)


### ndarray의 초기화
- ndarray를 만드는 다양한 방법이 존재

In [24]:
# 모든 값이 0인 2*3 배열 생성
zero_mat = np.zeroms((2,3))
zero_mat

AttributeError: module 'numpy' has no attribute 'zeroms'