# 02-01 파이토치 패키지의 기본 구성

### 1. torch
- main namespace, 텐서 등 다양한 수학 함수가 포함되며 Numpy와 유사한 구조

### 2. torch.autograd
- 자동 미분을 위한 함수를 포함

### 3. torch.nn
- 신경망 구축을 위한 데이터 구조나 레이어가 정의
- RNN, LSTM, ReLU, MSELoss 등

### 4. torch.optim
- SGD를 중심으로 한 파라미터 최적화 알고리즘 구현 

### 5. torch.utils.data
- SGD의 반복연산을 실행할 때 사용하는 미지 배치용 유틸리티 함수 포함

### 6. torch.onnx
- ONNX라는 다른 딥러닝 프레임워크 간 모델을 공유할 때 사용하는 포맷

# 02-02 Tensor Manipulation 1
## 1. Vector, Matrix and Tensor
- 벡터 = 1차원 텐서, 2차원 행렬 = 2차원 텐서, 3차원텐서, 4차원 텐서, 5차원 텐서 등...
- 3D Tensor: NLP 분야에서 보통 (batch_size, 문장 길이, 단어 벡터의 차원)의 3차원 텐서 사용 

## 2. Numpy로 텐서 만들기
### 1) Numpy 기초 이해 

In [1]:
import numpy as np
t = np.array([0., 1., 2., 3., 4., 5., 6.,])
t

array([0., 1., 2., 3., 4., 5., 6.])

In [2]:
t.ndim

1

In [3]:
t.shape

(7,)

In [4]:
print(t[0], t[1], t[-1])

0.0 1.0 6.0


In [5]:
t[4:-1]

array([4., 5.])

### 2) 2D with Numpy

In [6]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
Rank  of t:  2
Shape of t:  (4, 3)


## 3. PyTorch Tensor Allocation (파이토치 텐서 선언)
### 1) 1D with PyTorch
### 2) 2D with PyTorch

In [7]:
import torch 

# 1차원 텐서
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
t


tensor([0., 1., 2., 3., 4., 5., 6.])

In [9]:
print(t.dim())
print(t.shape)
print(t.size())

1
torch.Size([7])
torch.Size([7])


In [10]:
print(t[0], t[1], t[-1])  # 인덱스로 접근
print(t[2:5], t[4:-1])    # 슬라이싱
print(t[:2], t[3:])       # 슬라이싱

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [11]:
# 2차원 텐서 
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [12]:
print(t.dim())  # rank. 즉, 차원
print(t.size()) # shape
print(t.shape)

2
torch.Size([4, 3])
torch.Size([4, 3])


In [13]:
print(t[:, 1])
print(t[:, 1].size())

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


### 3) Broadcasting
- 두 행렬 A,B가 있다고 해보자. 
- 행렬 A,B가 덧셈과 뺄셈을 하려면 크기가 같아야 한다. 
- 곱셈을 할 때는 A의 마지막 차원과 B의 첫번째 차원이 일치해야한다 .
- 딥러닝을 하면 불가피하게 크기가 다른 행렬 또는 텐서에서 사칙 연산을 수행하게 될때 **브로드캐스팅**을 한다. 

In [14]:
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
m1 + m2 

tensor([[5., 5.]])

In [15]:
# Vector + Scalar
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3])
m1 + m2 

tensor([[4., 5.]])

In [16]:
# 2*1 vector + 1*2 vector -> broadcasting
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3], [4]])
m1 + m2

tensor([[4., 5.],
        [5., 6.]])

### 4) 자주 사용되는 기능들
#### 4-1) 행렬 곱셈과 곱셈의 차이

In [17]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [18]:
# 동일한 위치의 원소끼리의 element-wise 곱셈
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2)) 

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


#### 4-2) Mean

In [19]:
t = torch.FloatTensor([1,2])
t.mean()

tensor(1.5000)

In [20]:
t = torch.FloatTensor([[1, 2], [3, 4]])
t.mean()

tensor(2.5000)

In [23]:
t.mean(dim=0) # 첫번째 차원인 행을 제거

tensor([2., 3.])

In [24]:
t.mean(dim=1) # 두번째 차원인 열을 제거 

tensor([1.5000, 3.5000])

In [25]:
t.mean(dim=-1) # 마지막 차원인 열을 제거

tensor([1.5000, 3.5000])

#### 4-3) Sum

In [27]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.sum())
print(t.sum(dim=0)) # 행을 제거 [4,6]
print(t.sum(dim=1)) # 열을 제거
print(t.sum(dim=-1)) # 열을 제거 

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


#### 4-4) Max, ArgMax

In [28]:
t = torch.FloatTensor([[1, 2], [3, 4]])
t.max()

tensor(4.)

In [30]:
t.max(dim=0) # argmax도 함께 리턴, 열의 최대값과 인덱스 반환

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))

In [31]:
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [32]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


# 02-03 Tensor Manipulation 2
### 1) View - 원소의 수를 유지하며 텐서의 크기 변경 , 매우 중요! 
- 파이토치 텐서의 view는 numpy에서 reshape와 같은 역할
- view는 기본적으로 변경 전과 변경 후의 텐서 안의 원소의 개수가 유지되어야 한다.
- 파이토치의 view는 사이즈가 -1로 설정되면 다른 차원으로부터 해당 값을 유추한다. 

In [33]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

In [34]:
ft.shape

torch.Size([2, 2, 3])

##### 1-1) 3차원 텐서를 2차원 텐서로 변경

In [36]:
ft.view([-1,3])

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [40]:
# -1은 잘 모르겠으니 파이토치에게 맡기고, 3은 두번째 차원의 길이가 3 (?,3)으로 변경
# (2*2*3) -> (4*3) ==> 12 
ft.view([-1,3]).shape

torch.Size([4, 3])

#### 1-2) 3차원 텐서의 크기 변경
- 3차원 텐서 -> 3차원 텐서는 유지하되, shape를 바꾸는 작업
- (2* 2 *3) -> (? * 1 *3)

In [41]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### 2) Squeeze - 1인 차원을 제거

In [42]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [43]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


### 3) Unsqueeze - 특정 위치에 1인 차원 추가 

In [44]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [45]:
print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [46]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape) # view로도 차원 1 추가 가능 

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [47]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [48]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


### 4) Type Casting - 자료형 변환


In [49]:
lt = torch.LongTensor([1,2,3,4])
lt

tensor([1, 2, 3, 4])

In [50]:
lt.float()

tensor([1., 2., 3., 4.])

In [51]:
bt = torch.ByteTensor([True, False, False])
bt

tensor([1, 0, 0], dtype=torch.uint8)

In [52]:
bt.long()

tensor([1, 0, 0])

In [53]:
bt.float()

tensor([1., 0., 0.])

### 5) Concatenate
- 두 텐서의 연결 

In [54]:
x = torch.FloatTensor([[1,2], [3,4]])
y = torch.FloatTensor([[5,6], [7,8]])
torch.cat([x,y], dim = 0) # 첫번째 차원 늘리기 (2*2) -> (4*2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [56]:
torch.cat([x,y], dim=1) # (2*2) -> (2*4)

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])

### 6) Stacking
- 스택킹은 연결이지만 많은 연산을 포함

In [60]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

torch.stack([x,y,z]) # 3개의 벡터가 (3*2)텐서로 변환 

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [61]:
torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [62]:
torch.stack([x,y,z], dim=1) # (2*3) 텐서

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### 7) ones_like, zeros_like - 0으로 채워진 텐서, 1로 채워진 텐서 

In [63]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])

In [64]:
torch.ones_like(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [65]:
torch.zeros_like(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

### 8) In-place Operation (덮어쓰기 연산)

In [66]:
x = torch.FloatTensor([[1, 2], [3, 4]])
x.mul(2.)

tensor([[2., 4.],
        [6., 8.]])

In [67]:
# 연산자 뒤에 _ 를 붙이면 기존의 값을 덮어쓰기 함
x.mul_(2.)

tensor([[2., 4.],
        [6., 8.]])

In [68]:
x

tensor([[2., 4.],
        [6., 8.]])

# 02-04 Python class

## 1. Function과 Class의 차이
- Function: 서로의 값에 영향을 주지 않고 서로 다른 연산, 각각의 함수를 만들어야한다.
- Class: 두 개의 객체를 독립적으로 연산 가능, 클래스는 1개만 선언하면 된다. 

In [69]:
result = 0
def add(num):
    global result
    result += num
    return result 

print(add(4))
print(add(3))

4
7


In [70]:
result1 = 0
result2 = 0

def add1(num):
    global result1
    result1 += num
    return result1

def add2(num):
    global result2
    result2 += num
    return result2

print(add1(3))
print(add1(4))
print(add2(3))
print(add2(7))

3
7
3
10


In [71]:
class Calculator:
    def __init__(self):
        self.result = 0
    
    def add(self, num):
        self.result += num
        return self.result
cal1 = Calculator()
cal2 = Calculator()

In [72]:
print(cal1.add(3))
print(cal1.add(4))
print(cal2.add(3))
print(cal2.add(7))

3
7
3
10
